MusicApp/config/routes.rb
Rails.application.routes.draw do
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"

    root "sessions#new"

    resources(:users, only: [:new, :create, :show])
    resources(:bands)

    resource(:session, only: [:new, :create, :destroy])
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

MusicApp/app/models/band.rb
class Band < ApplicationRecord
    validates(:name, presence: true, uniqueness: true)
end

MusicApp/app/models/user.rb
class User < ApplicationRecord

    validates(:email, :session_token, presence: true, uniqueness: true)
    validates(:password_digest, presence: true)
    validates(:password, length: {minimum: 8, allow_nil: true})
    before_validation(:ensure_session_token)

    attr_reader(:password)

    # FIGVAPEBR
    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        if user && user.is_password?(password)
            return user
        else
            return nil
        end
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = generate_unique_session_token
        self.save!
        self.session_token
    end

    private
    def generate_unique_session_token
        loop do
            session_token = SecureRandom::urlsafe_base64
            return session_token if User.find_by(session_token: session_token).nil?
        end
    end

    def ensure_session_token
        self.session_token ||= generate_unique_session_token
    end
end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # CHR(R)LLL

    helper_method(:current_user, :logged_in?)

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def require_logged_out
        redirect_to root if logged_in? # check later?
    end

    def logged_in?
        !!current_user
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout!
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end

end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    before_action(:set_band, only: [:show, :edit, :update, :destroy])

    def index
        @bands = Band.all
        render :index
    end

    def create
        @band = Band.new(band_params)

        if @band.save
            flash.now[:messages] = ["Band Successfully Created"]
            render :show
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end
    end

    def new
        @band = Band.new
        render :new
    end

    def edit
        render :edit
    end

    def show
        render :show
    end

    def update
        if @band.save
            flash.now[:messages] = ["Band Successfully Edited"]
            render :show
        else
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end
    end

    def destroy
        @band.destroy
        render :index
    end

    private
    def band_params
        params.require(:band).permit(:name)
    end

    def set_band
        @band = Band.find_by(id: params[:id])
    end

end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
        render :new
    end

    def create
        email = params[:user][:email]
        password = params[:user][:password]

        @user = User.find_by_credentials(email, password)

        if @user
            login!(@user)
            redirect_to user_url(@user)
        else
            @user = User.new
            flash.now[:errors] = ["Invalid Credentials"]
            render :new
        end
    end

    def destroy
        logout!
        # flash successful logout?
        flash.now[:messages] = ["Logout Successful!"]
        @user = User.new
        render :new # redirect to login page?
    end
end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new

        render :new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find_by(id: params[:id])

        render :show
    end

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/views/bands/_form.html.erb
<% if type == :edit %>
    <% action_url = band_url(@band) %>
<% else %>
    <% action_url = bands_url %>
<% end %>

<form action="<%= action_url %>" method="POST" class="band-form">
    <% if type == :edit %>
        <input type="hidden" name="_method" value="PATCH">
    <% end %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Band Name:
        <input type="text" name="band[name]" value="<%= @band.name %>">
    </label>

    <input type="submit" value="<%= type == :edit ? 'Update Band' : 'Create Band' %>">
</form>

MusicApp/app/views/bands/edit.html.erb
<% render 'form', type: :edit %>

MusicApp/app/views/bands/index.html.erb
<div class="bands-container">
    <% @bands.each do |band| %>
        <form action="<%= band_url(band.id) %>" method="GET">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="submit" value="<%= band.name %>" class="band-button">
        </form>
    <% end %>
</div>

MusicApp/app/views/bands/new.html.erb
<% render 'form', type: :new %>

MusicApp/app/views/bands/show.html.erb
<h2>Welcome to <%= @band.name %>'s Show Page</h2>

MusicApp/app/views/layouts/_form.html.erb
<% if type == :new_user %>
    <% action_url = users_url %>
<% else %>
    <% action_url = session_url %>
<% end %>

<div class="main-form">
    <form action="<%= action_url %>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

        <label for="email">Email:</label>
        <input type="text" id="email" name="user[email]" value="<%= user.email %>" >
        <br>

        <label for="password">Password:</label>
        <input type="password" id="password" name="user[password]" value="" >
        <br>

        <input type="submit" value="<%= type == :new_user ? 'Create Account' : 'Log in' %>">
    </form>
</div>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Audiowide">
    <%= stylesheet_link_tag "application" %>
    <%= stylesheet_link_tag "custom" %>
  </head>

  <body>

    <nav>
        <h1>Music App</h1>

        <% if logged_in? %>
            <form action="<%= session_url %>" method="POST">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

                <input type="hidden" name="_method" value="DELETE">
                <input type="submit" value="Log Out!" class="button-1">
            </form>
        <% else %>
            <div class="login-buttons">
                <form action="<%= new_user_url %>" method="GET">
                    <input type="submit" value="Sign Up!" class="button-1">
                </form>
                <form action="<%= new_session_url %>" method="GET">
                    <input type="submit" value="Log In" class="button-1">
                </form>
            </div>
        <% end %>

    </nav>

    <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
            <p class="error-message"><%= error %></p>
        <% end %>
    <% end %>

    <% if flash[:messages] %>
        <% flash[:messages].each do |message| %>
            <p><%= message %></p>
        <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>

MusicApp/app/views/users/new.html.erb
<%= render 'layouts/form', user: @user, type: :new_user %>

MusicApp/app/views/users/show.html.erb
<h2>Welcome, <%= @user.email %></h2>